name: deckmind
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.2
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/data/games.json
